import type { Metadata } from "next";
import { Anek_Odia, Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/redux/ReduxProvider";

// const anek_odia = Anek_Odia({ subsets: ["latin"] });
const anek_odia = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Frida Research Engine",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
            <ReduxProvider>
			<body className={anek_odia.className}>
				<main className="relative flex min-h-screen flex-col">
					<Navbar />
					{children}
				</main>
			</body>
            </ReduxProvider>
		</html>
	);
}
